CREATE DATABASE QLSV;
USE QLSV;
CREATE TABLE CLASS(
	ID INT PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL
);

CREATE TABLE TEACHER (
	ID INT PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    COUNTRY NVARCHAR(50)
);

CREATE TABLE STUDENT(
	ID INT PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL,
    AGE INT NOT NULL,
    COUNTRY NVARCHAR(50)
);

